### ISSUE TITLE
Laravel integration 

### ISSUE THREAD

**Issue by Jijiri89** [Parables/arkesel-sdk#22]
Please, I want to integrate your package into my laravel project for sms notification
I gone through your documentation but I need some clarification to enable me to the integration.
Please my problem is that, after installing your package through composer and publishing it, where do I get access to the facade in my project directory?

**Comment by Parables** [comment]
Hello @Jijiri89 

Please accept my sincere apologies for not responding sooner... 

I am not sure I understand your question correctly. 
It would be super helpful if you can provide a sample code of your use-case.
Knowing how you intend to use this package will help to better assist you.

All the same, using this package is really simple, as explained in the docs.

There is the global `arkeselSms()` function that you can call from anywhere within your app
```php
$response = arkeselSms()
    ->message('Hello World')
    ->recipients(["233234567890", "233234567890"])
    ->send();
```

You can also use the facade as you mentioned this way from anywhere with your app
```php
$response = ArkeselSms::make()
    ->message('Hello World')
    ->recipients(["233234567890", "233234567890"])
    ->send();
```

I am standing by for your response... Please reply and let me know if I have addressed your issue

**Comment by Parables** [comment]
Closing this issue since it has been inactive for a while now

**Comment by Jijiri89** [comment]
Thanks so much for your response. Now I am OK with it.
